### ISSUE TITLE
Section in install.pp line 126 uses puppet --future parser

### ISSUE THREAD

**Issue by marcinbojko** [covermymeds/puppet-sentry#23]
Whole section:
`# Install any extensions we might have been given. We install these
  # *after* Sentry to ensure the correct version of Sentry is installed
  validate_array($extensions)
  $extensions.each |String $extension| {
    python::pip { $extension:
      require => Python::Pip['sentry'],
    }
  }`

uses 'future' parses which makes module unusable on other setting, and with The Foreman for example.
Is it possible to switch to classic mode?

**Comment by adamcstephens** [comment]
Hi @marcinbojko,

Unfortunately, we have committed to using the future parser features moving forward with this module. I've updated the README to make this clearer (it was already in the CHANGELOG).

-adam

**Comment by marcinbojko** [comment]
```
Hi adam
  thanks for the update.
  mb

  On 01.06.2016 15:39, Adam Stephens wrote:


  Hi @marcinbojko,
  Unfortunately, we have committed to using the future parser
    features moving forward with this module. I've updated the
    README to make this clearer (it was already in the CHANGELOG).
  -adam
  —
    You are receiving this because you were mentioned.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.
```
